<template><div><h1 id="zeile-入门" tabindex="-1"><a class="header-anchor" href="#zeile-入门"><span>Zeile 入门</span></a></h1>
<h2 id="创建项目" tabindex="-1"><a class="header-anchor" href="#创建项目"><span>创建项目</span></a></h2>
<p>此节暂时省略</p>
<h2 id="从-say-开始" tabindex="-1"><a class="header-anchor" href="#从-say-开始"><span>从 <code v-pre>say</code> 开始!</span></a></h2>
<p>语言是故事中最重要的核心部分，让我们从让一名角色说话开始。
在 Zeile 中，这可以用一行代码实现：</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"你好！"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: .</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">soyo</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// 让素世说：“你好！”</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>这就完成了，这一行代码是一个故事的完整脚本。
你不需要提供其他额外信息，例如角色的全名 —— Zeile 负责推断它们。</p>
<h2 id="角色" tabindex="-1"><a class="header-anchor" href="#角色"><span>角色</span></a></h2>
<p>让我们进一步看看在上一节中写的这行代码。<code v-pre>.soyo</code> 指的是角色<em>长崎素世</em>。
我们可以把这个表达展开为更完整的版本：</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">soyo</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>这应该很好理解，我们在指代“角色”(<em>Character</em>)中的“素世”(<em>soyo</em>)，
所以我们写 <code v-pre>Character.soyo</code>。然后就可以把它放进前面说的 <code v-pre>say</code> 里了：</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"你好！"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">soyo</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>这行代码和前一节中的代码都一样是有效的。因为 Zeile 足够聪明，
知道 <code v-pre>by:</code> 后面的值一定是个角色，然后为你<strong>推断</strong>了 <code v-pre>Character</code> 这部分，
所以你可以不用显式地把这部分写出来。
如果你在另一个 Zeile 不能推断 <code v-pre>Character</code> 前缀的地方指代一个角色，
则必须把这部分显式写出来，就像上面这样。</p>
<h2 id="活动起来" tabindex="-1"><a class="header-anchor" href="#活动起来"><span>活动起来</span></a></h2>
<p>让我们将角色显示在屏幕上并让她们做一些动作，来让我们的故事看起来更好。
首先，我们需要一名角色，这已经在上一节中提到过了：</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">soyo</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>接下来，在这后面添加一个操作。我们想要先让素世出现(<em>show</em>)在屏幕上：</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">soyo</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">show</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">at</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: .</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">center</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>使用一个点(.)来分隔角色与操作。运行这行代码后，素世现在就在屏幕的中心(<em>center</em>)了。</p>
<div class="hint-container tip">
<p class="hint-container-title">提示</p>
<p>类似于 <code v-pre>.soyo</code> 这样的表达，<code v-pre>.center</code> 是 <code v-pre>Position.center</code> 的缩写，
Zeile 可以推断这里的 <code v-pre>Position</code>。</p>
</div>
<p>接下来可以让素世做个动作，让我们继续编辑代码：</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">soyo</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">show</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">at</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: .</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">center</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">).</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">act</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"nf02"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>这行代码的意思是“让素世出现在屏幕的中心，随后让她做名为 ‘nf02’ 的动作”。
你可以在 Greatdori! 的 Live2D 浏览器中找到动作的完整列表，
代码补全也会在你输入的时候向你推荐可用的动作。</p>
<div class="hint-container tip">
<p class="hint-container-title">练习</p>
<p><code v-pre>nf02</code> 是我最喜欢的动作，修改这行代码来让你最喜欢的角色做你最喜欢的动作。</p>
</div>
<h2 id="环境" tabindex="-1"><a class="header-anchor" href="#环境"><span>环境</span></a></h2>
<p>现在你知道了如何让角色说点东西并让她动起来。
环境这一块怎么说？现在背景一片漆黑，也没有任何声音。
让我们先加一张背景(<em>Background</em>)图：</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">Background.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">change</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">to</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"scenario102/bg01021.png"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>这里的“scenario102/bg01021.png”是一个<em>路径</em>，用于唯一地定位一个资源。
我们将在以后深入讨论这个。现在，你可以从代码补全窗口中选一张你喜欢的图片。</p>
<p>若要更改背景音乐，将上面代码中的 <code v-pre>Background</code> 换成 <code v-pre>BGM</code>，
然后把路径改为指向某个音频的路径就好了。这也可以通过自动补全窗口来查找。</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">BGM.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">change</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">to</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"04_nobiri/04_Nobiri.mp3"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="自定义角色" tabindex="-1"><a class="header-anchor" href="#自定义角色"><span>自定义角色</span></a></h2>
<p>Zeile 已经为你准备了一些角色的预设，这已经在前面的<em>角色</em>一节中说到了。
让我们自己自定义一个角色！</p>
<p>首先，一个角色有这三个属性：</p>
<ul>
<li>ID (标识符)</li>
<li>名称 (<em>name</em>)</li>
<li>Live 2D 路径</li>
</ul>
<p>每个角色都有一个整数 ID。你可以在 Greatdori! 的角色详情页中找到一名角色的 ID。
例如，素世的 ID 是 <code v-pre>39</code>，因此我们可以这样表示她：</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">id</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">39</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>那其他的参数呢？Zeile 在为你推断它们！如果向 <code v-pre>Character</code> 提供的 ID 是已知的
（即，可以在 Greatdori! 的角色页中找到它），则 Zeile 可以为你推断名称和 Live 2D 路径。</p>
<div class="hint-container note">
<p class="hint-container-title">注</p>
<p>推断的名称基于你的地区设置。
如果你正在使用 Zeile 编辑器，你可以在<em>项目导航栏 → 元数据 → 地区</em>处更改这项设置。</p>
<p>推断的 Live 2D 总是角色的第一个季节服装。
你可以在 Greatdori! 的 Live 2D 浏览器中找到季节服装的列表。</p>
</div>
<p>如果你想要指定一个与推断名称不同的名称，像这样在 ID 后面添加名称(<em>name</em>)：</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">id</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">39</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">name</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"栗色黑洞"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>如果你想要指定 Live 2D 路径，在后面接着添加：</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">id</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">39</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">name</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"栗色黑洞"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">live2d</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"039_dream_festival_3_ur"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// 或者，如果你想用推测的名称</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">id</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">39</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">live2d</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"039_dream_festival_3_ur"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>完成自定义角色后，你就可以在任何需要角色的地方使用它，比如 <code v-pre>say</code>：</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"你好！"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">id</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">39</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">live2d</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"039_dream_festival_3_ur"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="为一个值命名" tabindex="-1"><a class="header-anchor" href="#为一个值命名"><span>为一个值命名</span></a></h2>
<p>我们已经在上一节中自定义了一个角色，并且知道了如何使用它。
但是随着 <code v-pre>say</code> 越来越多，这看起来就有点乱了：</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"你好！"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">id</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">39</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">live2d</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"039_dream_festival_3_ur"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"我是长崎素世"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">id</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">39</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">live2d</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"039_dream_festival_3_ur"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"贵安"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">id</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">39</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">live2d</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"039_dream_festival_3_ur"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们需要写一大堆重复的 <code v-pre>Character</code>，如果以后想更改一些参数就更有难了
—— 我们必须得去一个个更改每一行的 <code v-pre>Character</code>。</p>
<p>使用 <code v-pre>let</code> 来为一个不变的值指定一个名称，然后你就可以通过这个名称来引用它：</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">let</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> mySoyo = </span><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">id</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">39</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">live2d</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"039_dream_festival_3_ur"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"你好！"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: mySoyo)</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"我是长崎素世"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: mySoyo)</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"贵安"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: mySoyo)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="hint-container note">
<p class="hint-container-title">注</p>
<p>一个值的名称可以是任何文本，甚至可以是一组 Emoji！
但是，它不能以数字开始，且不能包含除了下划线(<code v-pre>_</code>)以外的标点符号。</p>
</div>
<p>我们把一个值的名称叫做“变量”。注意它在声明后并不能被改变，
并且你不能使用前面的变量已经使用过的名字。</p>
<p>让我们定义更多变量并创作一个简短的故事！</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">let</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> anon = </span><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">anon</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">let</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> soyo = </span><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">soyo</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">let</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> soyoHome = </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"scenario102/bg01021.png"</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">Background.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">change</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">to</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: soyoHome)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">BGM.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">change</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">to</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"04_nobiri/04_Nobiri.mp3"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// 悠闲的小曲</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">anon.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">show</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">at</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: .</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">left</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">soyo.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">show</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">at</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: .</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">right</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"小爱音，我去沏一杯红茶"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: soyo)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">soyo.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">act</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"nf03"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"OK~ 谢谢Soyorin~"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: anon)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">anon.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">act</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"nf05"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">soyo.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">hide</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">()</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">anon.</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">move</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">to</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: .</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">center</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="GettingStartedProject.zip">下载示例项目</a></p>
<div class="hint-container tip">
<p class="hint-container-title">提示</p>
<p>上面代码中的所有空行都是可选的 —— Zeile 会全部忽略掉。
我们这样做是为了分隔代码的不同部分来让它更有可读性。
<code v-pre>//</code> 后面的内容是<em>注释</em>，它们也全都会被 Zeile 忽略掉。</p>
</div>
</div></template>


