<template><div><h1 id="the-type-system" tabindex="-1"><a class="header-anchor" href="#the-type-system"><span>The Type System</span></a></h1>
<p>Learn the core idea with values in Zeile — types.</p>
<p>In Zeile, every value has a type. Variables are representations of values,
so they also have types.</p>
<h2 id="basic-types" tabindex="-1"><a class="header-anchor" href="#basic-types"><span>Basic Types</span></a></h2>
<p>There're four basic types in Zeile:</p>
<ul>
<li><code v-pre>Int</code>: Integers, such as <code v-pre>0</code>, <code v-pre>42</code>, <code v-pre>-100</code>.</li>
<li><code v-pre>Float</code>: Numbers with fractional component,
also known as <em>floating-point numbers</em>, such as <code v-pre>3.14159</code>, <code v-pre>-0.1</code>, <code v-pre>3.0</code>.</li>
<li><code v-pre>String</code>: Texts, such as <code v-pre>&quot;Hello!&quot;</code>, <code v-pre>&quot;123&quot;</code>, <code v-pre>&quot;😋&quot;</code>.</li>
<li><code v-pre>Bool</code>: Boolean, which is either <code v-pre>false</code> or <code v-pre>true</code>.</li>
</ul>
<p>A variable's type is its initial value's type.
For example:</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">let</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> hello = </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"Hello!"</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// The variable “hello” has the type “String”</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">let</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> myNumber = </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">42</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// The variable “myNumber” has the type “Int”</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="other-types" tabindex="-1"><a class="header-anchor" href="#other-types"><span>Other Types</span></a></h2>
<p>Beside the basic types, other types can represent more information.
For example, <code v-pre>Character</code> is also a type.</p>
<div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-"><span class="line"><span>let kasumi = Character.kasumi</span></span>
<span class="line"><span>// The variable “kasumi” has the type “Character”</span></span>
<span class="line"><span></span></span>
<span class="line"><span>let coolSoyo = Character(id: 39, live2d: "039_live_event_289_ur")</span></span>
<span class="line"><span>// The variable “coolSoyo” also has the type “Character”</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="using-types" tabindex="-1"><a class="header-anchor" href="#using-types"><span>Using Types</span></a></h2>
<p>Let's start from calling <code v-pre>say</code>. We call clauses that perform specific tasks
a <em>function</em>. A function may take some inputs, we call them <em>arguments</em>.
For example, in this code:</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"Hello!"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: .</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">soyo</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>We're calling a function named <code v-pre>say</code>, <code v-pre>&quot;Hello!&quot;</code> and <code v-pre>.soyo</code> are arguments
passed into the function. <code v-pre>by</code> is the <em>label</em> of the second argument.</p>
<p>A function always takes arguments with specific types in order.
Different functions may have the same name, but there argument count,
type, or label are different. We use a expression like this to uniquely
refer to a function:</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">_</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">String</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>In this expression, <code v-pre>say</code> is the name of the function.
The first argument should be a <code v-pre>String</code>, and has no argument label,
we use an underscore(<code v-pre>_</code>) to represent this.
The second argument should be a <code v-pre>Character</code>, and has an argument label <code v-pre>by</code>.</p>
<p>The value you passed into a function as an argument must match the
type defination. This line of code below is <strong>invalid</strong>:</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: .</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">soyo</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// Cannot convert value of type 'Int' to expected argument type 'String'</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="creating-values-from-types" tabindex="-1"><a class="header-anchor" href="#creating-values-from-types"><span>Creating Values from Types</span></a></h2>
<p>When you're writting something like “calling a type”,
you're actually calling a special function that creates a value of this type.
We call this kind of functions <em>initializers</em>.</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">id</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">39</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>This line of code calls an initializer of the type <code v-pre>Character</code>,
which creates a value of this type. This is actually an abbreviation,
we're omitting the <code v-pre>.init</code> in this call.</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">init</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">id</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">39</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>This line of code does the exactly same thing as the previous code.</p>
<p>When Zeile is inferring the type for you, you have to type the <code v-pre>.init</code>
explicitly:</p>
<div class="language-zeile line-numbers-mode" data-highlighter="shiki" data-ext="zeile" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-zeile"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"Hello!"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: .</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">init</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">id</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">39</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// Or, if you don't like this abbreviation</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">say</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"Hello!"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">by</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#0184BC;--shiki-dark:#E5C07B">Character</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">id</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">: </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">39</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


